"""AP exceptions dashboard.

Four panels, deliberately. A KPI strip, an aging chart, vendor exposure, and a
filterable exception table. Reads only the views in sql/002_views.sql, never the
base tables.

Run with:  streamlit run dashboard/app.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import altair as alt
import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ap import db  # noqa: E402

st.set_page_config(page_title="AP Exceptions", page_icon="◱", layout="wide")

SEVERITY_ORDER = {"critical": 0, "warn": 1, "info": 2}

RULE_LABELS = {
    "DUP_EXACT": "Exact duplicate",
    "DUP_NEAR": "Near duplicate",
    "DUP_FUZZY_VEND": "Duplicate across vendor spellings",
    "OVERDUE_30": "Over 30 days past due",
    "OVERDUE_60": "Over 60 days past due",
    "OVERDUE_90": "Over 90 days past due",
    "AMT_THRESHOLD": "Above approval threshold",
    "MISSING_GL": "Missing GL code",
    "FUTURE_DATE": "Future-dated invoice",
    "LINE_MISMATCH": "Lines do not match header",
}


@st.cache_data(ttl=60)
def load(sql: str) -> pd.DataFrame:
    with db.connect() as conn:
        return pd.DataFrame(db.query(conn, sql))


def money(value) -> str:
    return f"${float(value or 0):,.2f}"


st.title("Accounts Payable — Exceptions & Aging")
st.caption(
    "Synthetic data only. Generated by `python -m ap.generate`; no real vendor "
    "information appears anywhere in this project."
)

try:
    kpis = load("SELECT * FROM v_kpis").iloc[0]
    aging = load("SELECT * FROM v_aging_summary")
    vendors = load(
        "SELECT * FROM v_vendor_exposure ORDER BY open_balance DESC LIMIT 10"
    )
    exceptions = load("SELECT * FROM v_open_exceptions")
except Exception as exc:  # noqa: BLE001
    st.error(
        "Could not reach the database. Start it with `docker compose up -d` and "
        "load data with `make pipeline`."
    )
    st.exception(exc)
    st.stop()

# ------------------------------------------------------------------ KPI strip
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total open AP", money(kpis["total_open_ap"]))
col2.metric(
    "Past due",
    money(kpis["past_due_amount"]),
    delta=f"{int(kpis['past_due_count'])} invoices",
    delta_color="inverse",
)
col3.metric("Duplicate flags", int(kpis["duplicate_flags"]))
col4.metric(
    "Duplicate exposure",
    money(kpis["duplicate_exposure"]),
    help="Total value of invoices flagged by any duplicate rule. This is the "
         "amount at risk of being paid twice, not a confirmed loss.",
)

st.divider()

# ------------------------------------------------------------- Aging + vendors
left, right = st.columns([1, 1])

with left:
    st.subheader("Aging")
    if aging.empty:
        st.info("No open invoices.")
    else:
        # v_aging_summary returns sort_order precisely so the buckets read
        # current -> 90+ left to right, which is the whole visual argument the
        # chart makes. st.bar_chart orders categories as strings, and digits
        # sort before letters, so "current" lands on the far right -- putting
        # the healthiest bucket where a reader expects the most delinquent one.
        # Pinning the scale domain to sort_order is what keeps the chart and the
        # table below it telling the same story.
        ordered = aging.sort_values("sort_order")
        chart_data = ordered.assign(total_amount=ordered["total_amount"].astype(float))
        chart = (
            alt.Chart(chart_data)
            .mark_bar()
            .encode(
                x=alt.X("aging_bucket:N", title=None,
                        sort=ordered["aging_bucket"].tolist()),
                y=alt.Y("total_amount:Q", title=None,
                        axis=alt.Axis(format="~s")),
                tooltip=[
                    alt.Tooltip("aging_bucket:N", title="Bucket"),
                    alt.Tooltip("invoice_count:Q", title="Invoices", format=","),
                    alt.Tooltip("total_amount:Q", title="Amount", format=",.2f"),
                ],
            )
        )
        st.altair_chart(chart, width="stretch", height=280)
        display = aging[["aging_bucket", "invoice_count", "total_amount"]].copy()
        display["total_amount"] = display["total_amount"].map(money)
        display.columns = ["Bucket", "Invoices", "Amount"]
        st.dataframe(display, hide_index=True, width="stretch")

with right:
    st.subheader("Top vendors by open balance")
    if vendors.empty:
        st.info("No vendor exposure to show.")
    else:
        display = vendors[
            ["vendor_name", "open_invoices", "open_balance",
             "past_due_amount", "worst_days_past_due"]
        ].copy()
        for col in ("open_balance", "past_due_amount"):
            display[col] = display[col].map(money)
        display.columns = ["Vendor", "Open", "Balance", "Past due", "Worst days"]
        st.dataframe(display, hide_index=True, width="stretch", height=380)

st.divider()

# ------------------------------------------------------------ Exception browser
st.subheader("Exceptions")

if exceptions.empty:
    st.success("No open exceptions.")
    st.stop()

exceptions["rule_label"] = exceptions["rule_code"].map(RULE_LABELS).fillna(
    exceptions["rule_code"]
)

filter_col1, filter_col2 = st.columns([2, 1])
with filter_col1:
    chosen = st.multiselect(
        "Rule",
        options=sorted(exceptions["rule_code"].unique()),
        format_func=lambda code: RULE_LABELS.get(code, code),
        placeholder="All rules",
    )
with filter_col2:
    severities = st.multiselect(
        "Severity",
        options=sorted(exceptions["severity"].unique(), key=SEVERITY_ORDER.get),
        placeholder="All severities",
    )

filtered = exceptions
if chosen:
    filtered = filtered[filtered["rule_code"].isin(chosen)]
if severities:
    filtered = filtered[filtered["severity"].isin(severities)]

filtered = filtered.sort_values(
    by=["severity", "amount"],
    key=lambda s: s.map(SEVERITY_ORDER) if s.name == "severity" else s,
    ascending=[True, False],
)

st.caption(
    f"{len(filtered):,} of {len(exceptions):,} exceptions · "
    f"{money(filtered['amount'].astype(float).sum())} in flagged value"
)

table = filtered[
    ["severity", "rule_label", "vendor_name", "invoice_number", "invoice_date",
     "due_date", "amount", "related_invoice_number", "detail"]
].copy()
table["amount"] = table["amount"].map(money)
table.columns = [
    "Severity", "Rule", "Vendor", "Invoice", "Invoice date", "Due date",
    "Amount", "Related", "Detail",
]
st.dataframe(table, hide_index=True, width="stretch", height=420)

st.download_button(
    "Download as CSV",
    data=filtered.to_csv(index=False).encode("utf-8"),
    file_name="ap_exceptions.csv",
    mime="text/csv",
)
